"""Change terminal to string

Revision ID: 276a2dc78920
Revises: e9d2caab45f5
Create Date: 2025-06-26 23:53:35.056360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '276a2dc78920'
down_revision = 'e9d2caab45f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('access_code',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('access_code',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
