"""Change terminal to string

Revision ID: 3429a30806eb
Revises: 8ba12ded2ab2
Create Date: 2025-06-26 23:26:21.009424

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3429a30806eb'
down_revision = '8ba12ded2ab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.alter_column('terminal',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.alter_column('terminal',
               existing_type=sa.String(length=100),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)

    # ### end Alembic commands ###
