"""ADDED TRANSPORT COMPANY

Revision ID: 54228112fbf3
Revises: 5f890c6f735c
Create Date: 2025-06-27 15:18:19.049794

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '54228112fbf3'
down_revision = '5f890c6f735c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('memberIds', sa.ARRAY(sa.String()), nullable=False))
        batch_op.add_column(sa.Column('departureLoc', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('arrivalLoc', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('departureTOD', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('departureDate', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('arrivalDate', sa.DateTime(), nullable=False))
        batch_op.drop_column('arrival_time')
        batch_op.drop_column('departure_loc')
        batch_op.drop_column('member_ids')
        batch_op.drop_column('arrival_loc')
        batch_op.drop_column('origin')
        batch_op.drop_column('destination')
        batch_op.drop_column('departure_date')
        batch_op.drop_column('arrival_date')
        batch_op.drop_column('departure_tod')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('departure_tod', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('arrival_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('departure_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('destination', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('origin', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('arrival_loc', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('member_ids', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('departure_loc', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('arrival_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('arrivalDate')
        batch_op.drop_column('departureDate')
        batch_op.drop_column('departureTOD')
        batch_op.drop_column('arrivalLoc')
        batch_op.drop_column('departureLoc')
        batch_op.drop_column('memberIds')

    # ### end Alembic commands ###
