"""ADDED TRANSPORT COMPANY

Revision ID: 5f890c6f735c
Revises: c5b5f7bb3e08
Create Date: 2025-06-27 15:03:38.868717

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5f890c6f735c'
down_revision = 'c5b5f7bb3e08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vibes', sa.ARRAY(sa.String()), nullable=False))
        batch_op.alter_column('member_ids',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.alter_column('member_ids',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
        batch_op.drop_column('vibes')

    # ### end Alembic commands ###
