"""updated users

Revision ID: 5f8b3aa98653
Revises: bccd93586fe0
Create Date: 2025-06-25 14:36:11.643637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f8b3aa98653'
down_revision = 'bccd93586fe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.alter_column('company_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('vibes', sa.ARRAY(sa.String()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('vibes')
        batch_op.drop_column('date_of_birth')

    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.alter_column('company_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###
