"""Foreign Key Rel

Revision ID: 884ed0e1d974
Revises: 3c4afc85b01a
Create Date: 2025-06-21 19:49:07.156033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '884ed0e1d974'
down_revision = '3c4afc85b01a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###
