"""updated users

Revision ID: 8ba12ded2ab2
Revises: 5f8b3aa98653
Create Date: 2025-06-25 15:55:20.988591

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8ba12ded2ab2'
down_revision = '5f8b3aa98653'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('intro_video',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('vibes',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('vibes',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('intro_video',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
