"""ADDED TRANSPORT COMPANY

Revision ID: 932c91ea9f26
Revises: e41fc39ddbe4
Create Date: 2025-06-27 14:43:03.511742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '932c91ea9f26'
down_revision = 'e41fc39ddbe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seats', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('vehicle', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('member_ids', sa.ARRAY(sa.String()), nullable=True))
        batch_op.add_column(sa.Column('company', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('days', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('departure_loc', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('arrival_loc', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('departure_tod', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('departure_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('arrival_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('creator', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('fill', sa.Boolean(), nullable=True))
        batch_op.drop_column('seats_available')
        batch_op.drop_column('seats_total')
        batch_op.drop_column('transport_partner')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transport_partner', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('seats_total', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('seats_available', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('fill')
        batch_op.drop_column('creator')
        batch_op.drop_column('arrival_date')
        batch_op.drop_column('departure_date')
        batch_op.drop_column('departure_tod')
        batch_op.drop_column('arrival_loc')
        batch_op.drop_column('departure_loc')
        batch_op.drop_column('days')
        batch_op.drop_column('company')
        batch_op.drop_column('member_ids')
        batch_op.drop_column('vehicle')
        batch_op.drop_column('seats')

    # ### end Alembic commands ###
