"""ADDED TRANSPORT COMPANY

Revision ID: c5b5f7bb3e08
Revises: 9a2fd8eb1fe2
Create Date: 2025-06-27 14:50:14.193417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5b5f7bb3e08'
down_revision = '9a2fd8eb1fe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_column('days')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('days', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
