"""ADDED TRANSPORT COMPANY

Revision ID: e41fc39ddbe4
Revises: 276a2dc78920
Create Date: 2025-06-27 14:12:35.674731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e41fc39ddbe4'
down_revision = '276a2dc78920'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transport_partner', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('status')
        batch_op.drop_column('transport_partner')

    # ### end Alembic commands ###
