"""Change terminal to string

Revision ID: e9d2caab45f5
Revises: 3429a30806eb
Create Date: 2025-06-26 23:46:11.667473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9d2caab45f5'
down_revision = '3429a30806eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_code', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint(None, ['access_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('access_code')

    # ### end Alembic commands ###
